### ISSUE TITLE
I don't understand the complicated setting

### ISSUE THREAD

**Issue by kellyselden** [cafreeman/ember-object-update#5]
from [here](https://github.com/cafreeman/ember-object-update/blob/0a539fb4fdab047b9833985589e2ca73598f33cb/addon/utils/update.js#L10-L11)

What's the reason for not doing `set(obj, key, newValue);`?

**Comment by cafreeman** [comment]
It could probably just use `set` at this point.

Initially I went that direction for two reasons:
- I didn't want to mutate the value in place
- I expected that I'd want to expand this to being able to work with multiple properties at once, at which point assign would be a good option.

However, I haven't landed on a great API for working with multiple properties at once yet, so this `assign` has just been hanging out.

**Comment by kellyselden** [comment]
ok Thanks
